Fix read regression for array with full uint dimension domain
The change in PR #2361 (f731ffc386ac3f) prevents reading existing
arrays written with TileDB 2.2 and having a dimension domain of:

  (0, typemax(uint{8,16,32,64})

For example, reading an array with the following dimension:

```
Dim(name='partition_id', domain=(0, 65535), tile='1', dtype='uint16')
```

Fails with:
```
Error: Domain check failed; Domain range (upper + lower + 1) is larger than the maximum unsigned number
```